---
- name: remi's repository present
  package:
    name: "{{ url_to_remis_repo }}"
    state: present
- name: mariadb's repository present
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: "http://yum.mariadb.org/{{ mysql_version }}/centos7-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
- name: latest misc packages installed
  yum:
    name: "{{ misc_packages }}"
    state: latest
#  notify: restart php-fpm
  tags: update
- name: latest php and php needed libraries installed
  yum:
    name: "{{ php_packages }}"
    state: latest
    enablerepo: remi-php72
  notify: restart php-fpm
  tags: update
- name: updated /etc/php-fpm.d/www.conf
  template:
    src: templates/www.conf
    dest: /etc/php-fpm.d/www.conf
  notify: restart php-fpm
- name: nginx's repository present
  yum_repository:
    name: nginx
    description: nginx
    baseurl: http://nginx.org/packages/mainline/centos/7/$basearch/
    gpgkey: http://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
- name: latest nginx packages installed
  yum:
    name: "{{ nginx_packages }}"
    state: latest
  notify: restart nginx
  tags: update

- name: flush handlers
  meta: flush_handlers
- name: php-fpm service enabled and started
  service:
    name: php-fpm
    state: started
    enabled: yes
- name: nginx group on /var/lib/php/
  shell: chgrp nginx /var/lib/php/*
  args:
    warn: False
- name: permissions on /var/lib/php/
  shell: chmod 2770 /var/lib/php/*
  args:
    warn: False

- name: http(s) firewall rules enabled
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - http
    - https
- name: selinux packages installed
  yum:
    name: "{{ selinux_packages }}"
    state: latest
  tags: update
- name: www target directory created
  file:
    path: /var/www/
    state: directory
    mode: 0755
    owner: root
    group: root
- name: selinux policies set on www
  sefcontext:
    target: '/var/www(/.*)?'
    setype: httpd_sys_content_t
    state: present
- name: http context remote connections with db possible
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes
- name: nginx enabled and started
  service:
    name: nginx
    state: started
    enabled: yes
...
